### ISSUE TITLE
Allow passing custom logger

### ISSUE THREAD

**Issue by sajal** [nbari/violetear#10]
Currently setting `router.LogRequests = true` , the requests logs are printed to stderr using default format. But I would like some way to pass a custom logger, example: [logrus](http://godoc.org/github.com/sirupsen/logrus#Logger) . Most logging implementations can be abstracted to a simple interface. 

If provided use it, otherwise use the default behavior.

**Comment by nbari** [comment]
Hi @sajal sorry for the late reply, I did some changes but after doing some tests I think is better to add the logger in a middleware.

In any case, I will try to see what could I do, mainly because the logger may need a custom [responseWriter](https://github.com/nbari/violetear/blob/master/response_writer.go#L10)  that depending on the logger it should be adapted. 

Any ideas are more than welcome.

**Comment by nbari** [comment]
@sajal What do you think about this: https://github.com/nbari/violetear/blob/master/violetear.go#L69

Basically,  ask for a function so that you can pass the response writer:
    
    // Logger
	Logger func(*ResponseWriter, *http.Request)

The default one to use is this one: https://github.com/nbari/violetear/blob/master/logger.go

Please give a try and let me know what you think.

**Comment by sajal** [comment]
Thats useful.  Looks like my code can use different logging paths based on status, etc...

**Comment by nbari** [comment]
I still doing some improvements, for the idea is that based on your logger you can manipulate the as required, the function needs to be:

   func logger(ww *ResponseWriter, r *http.Request) {}

And from there you can take or use any of the ResponseWriter, or the Request.

I will document this later, any ideas are more than welcome.

**Comment by nbari** [comment]
#12
